---
title: Fanzhou Liang
format:
    html:
        embed-resources: true
        css: styles.css
---


<!-- quarto add quarto-ext/fontawesome -->

::: {.info}

*Preferred Name: "Frank"*

{{< fa envelope >}} Email: fzlianguk@gmail.com | {{< fa phone >}} Phone: (+44) 07741948501

{{< fa brands github >}} GitHub: https://github.com/FzliangFrank

{{< fa brands linkedin >}} LinkedIn: https://www.linkedin.com/in/frank-liang/

{{< fa brands instagram >}} Instagram: https://www.instagram.com/franklyarts/

:::

### Profile

I am an experienced data professional with strong technical skills. I have the rare linguistic ability (I speak two languages) and am able to use several programming languages simultaneously (R, Python, SQL, JavaScript,even Visual Basic).
I am self-taught, highly motivated individual with a strong desire to learn. I have a passion for data. I seek to work with "true big data" in my next role. My calling is becoming a *Data Architect*. I aim to achieve this by starting work as a *Data Engineer* and challenging myself with heavier data volume.
Outside work, I enjoy art and music. I share digital drawings on my Instagram.

### Technical Skill

- Solid ELT (Extract Load Transform) skills for large geo-spatial data (typically 100,000 rows). For example:
    - Restore historical version of data using change logs table without time series database in pure PostgreSQL;
    - Create computationally efficient spatial join in the absence of GIS spatial indexing.
- Experience applying natural language processing (in commercial experience) and long paragraphs (Latent-Dirichlet-Allocation for my academic project). 
<!-- font-end -->
- Familiar with HTML, JavaScript and modern Web development frameworks such as DJANGO, ReactJS, and CSS; in fact, this CV is styled with CSS.

---

:::{.skill}

- R-programming (Tidyverse, igrap, tmap)
- Python (Pandas, Vega Altair)
- Postgre SQL + PostGIS
- Delta Lake

- Text-mining & Topic Modelling 
- Excel Macro & Visual Basics	

- R-Shiny application
- Neuro-Network
- Tensorflow

:::

---

### Work Experience 

04/2022 – present | **Full Fibre Limited** | **Data Analyst / System Developer** | Exeter, England, UK

<!-- *Automation* -->
<!-- - Automation, Application and Analytics: Automated re-occurring reporting (which is strictly data engineering); Build prototype application which can immediately benefit the business; Support decision making by providing ad-hoc analytics. -->
- Delivered the company’s first semi-automated data for fibre optic testing, which was three times faster than manual human input. 
- <!-- *Analytic* -->
- Delivered the company’s first data-driven financial reporting for the 2023 annual audit;
- Further automated several recurring reports, such as monthly service billing, annual carbon footprint, weekly build report;
- Participated in software procurement and advised the
<!-- *Application* -->
<!-- *Technology Leadership* -->
- Prototyped the first algorithm that would fully automate low-level planning using applied graph theory;
- The first to prototype the company’s fibre routing report and data validation strategy.
- I onboarded and buddied two mid-level colleagues during their first three months.
- Taught Postgres SQL training courses to several non-technical colleagues.

11/2021 - 01/2022 | **Marks and Spencer** | **General Customer Assistant** | Exeter, England, UK

- Customer service: delivering a great shopping experience for their customers.

### Voluntary Experiences 
03/2022 –05/2022 | **Exeter Green Party** | **Database Support** | Exeter

- Generic ad-hoc requests and data transformations. 
Worked with MySQL workbench.

11/2021 – 03/2022 | **Forage** | **KPMG Data Analytic Virtual Internship**| Virtual, at home 

- A virtual experience program that replicated the type of work KPMG graduates do with hypothetical data. 
- Data quality assessment: assess data quality and communicate with clients concisely. 
Data insights: explore data to propose efficient data-analytic models. 
 
09/2017 – 07/2018 | **Henan University of Technology** | Student Interpreter, 
Volunteered as an interpreter for foreign teaching staff. 
 
### Education 
2020 - 2021 | **University of Exeter** | **MSc Business Analytics** (merit)

- A data-centric master programme at one of the UK’s top 10 universities.  
- I was interviewed and successfully selected for the QTEM (Quantitative Technique for Economic and Management) program, but voluntarily withdrew to pursue visa status.   
- I achieved a distinction for my final project, in which I used topic modelling to identify research funding opportunities.  

2018 - 2020 | **Cardiff Metropolitan University** | **BA Business Management** with (Pathway) Human Resource Management (distinction, 1:1)

- A comprehensive education of best business practices with an extra focus on human resources management. 

2016 - 2018 | **Henan University of Technology** | **BA Human Resource Management** with Third Year Abroad

- Bachelor’s degree with robust mathematics (calculous, matrix, probability theory) foundation taught in the first year.  
- Taught and examined in full English; Achieved distinction for all English modules and awarded two scholarships.

### Professional Qualification
Since 2016 ACCA (5/13)

- Three Foundational module Plus
- Financial management (FM) 
- Performance management (PM)

### Portfolios
**Identify Research Funding Trends using Topic Modelling**. This is my Master's thesis. A project features Topic Modelling (LDA) and natural language processing for scope research funding for artificial intelligence. 
Full report here: https://github.com/FzliangFrank/Fzliang-UoE-2022

**Network Data Utility tool.** A R-Shiny App Tool Kit for interactive network visualisation. There are several prewritten modules which enable users to search a particular node or edges based on identity or attribute.
A demo of a web app written use this package is hosted on shiny.io: https://frank-the-tank.shinyapps.io/networkutils/

**LLoyd Bank Statement Reader** A Python package which reads a pdf bank statement into `.csv`, which I used to analyse my personal financial well-being.
Repo here: https://github.com/FzliangFrank/pdf_bank_statement.

### Interests & Activities 
{{< fa coffee >}} Café Laptop Hoper: Serial laptop hopper frowned by café owners across Cardiff and Exeter. Often found colonising coffee tables coding with my 14-inch MacBook.

{{< fa user-tie >}} Violin performance: few awards performing as a student violinist. Before the pandemic, I was briefly in a non-profit local Orchestra in Cardiff, South Wales

{{< fa paintbrush >}} Realistic Drawing: A less noisy hobby. I have a art Instagram: https://www.instagram.com/franklyarts/.

{{< fa brands spotify >}} My Playlist: Taylor Swift, Flume, French 79, IMANU...
